---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kubernetes-transform
  name: kubernetes-transform-cm
  namespace: xdhuxc
data:
  config.prod.yaml: |-
    

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubernetes-transform
  namespace: xdhuxc
  labels:
    app: kubernetes-transform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-transform
  template:
    metadata:
      labels:
        app: kubernetes-transform
    spec:
      volumes:
        - name: config
          configMap:
            name: kubernetes-transform-cm
      containers:
        - name: kubernetes-transform
          image: "127.0.0.1:5000/xdhuxc/kubernetes-transform:v0.0.1"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          volumeMounts:
            - name: config
              mountPath: /etc/xdhuxc/
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /kubernetes/api/v1/hi
              port: 8080
      imagePullSecrets:
        - name: xdhuxc-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-transform
  name: kubernetes-transform
  namespace: xdhuxc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: kubernetes-transform
